development:
  host:     localhost
  adapter:  postgresql
  username: postgres
  password: postgres
  database: homework
  encoding: unicode

production:
  host:     localhost
  adapter:  postgresql
  username: homework
  password: homework
  database: homework
  encoding: unicode
